# Node image'ını kullan
FROM node:16

# Çalışma dizinini ayarla
WORKDIR /app

# Paketleri yükle ve cache'le
COPY package*.json ./
RUN npm install

# Proje dosyalarını kopyala
COPY . .

# Build işlemini gerçekleştir
RUN npm run build

# Statik dosyaları serve eden basit bir web server kur
RUN npm install -g serve
CMD ["serve", "-s", "build"]

# Portu aç
EXPOSE 3000
