version: '4.31.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: circlar-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: typhon22
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: circlar-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: typhon22
      DB_HOST: db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
