# Generated by Django 4.2.4 on 2024-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('hours', models.IntegerField()),
                ('days', models.IntegerField()),
                ('is_short_task', models.BooleanField(default=False)),
            ],
        ),
    ]
