# Generated by Django 4.2.4 on 2024-06-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_shorttask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorttask',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='days',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.AddField(
            model_name='shorttask',
            name='is_short_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='New Task', max_length=100),
        ),
        migrations.AlterField(
            model_name='shorttask',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
