# Generated by Django 4.2.4 on 2024-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_name_shorttask_title_remove_task_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
