# Generated by Django 4.2.4 on 2024-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_shorttask_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttask',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='shorttask',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
