# Generated by Django 4.2.4 on 2024-06-02 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_shorttask_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=7.5, max_digits=5),
        ),
    ]
