# Generated by Django 5.0.6 on 2024-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_created_at_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=0, default=7.5, max_digits=5),
        ),
    ]
