# Generated by Django 5.0.6 on 2024-06-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_days_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
