# Generated by Django 5.0.6 on 2024-06-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_shorttask_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(),
        ),
    ]
