# Generated by Django 5.0.6 on 2024-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
