# Generated by Django 5.0.6 on 2024-06-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_rename_is_completed_task_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
