# Generated by Django 5.0.6 on 2024-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='meal_hours',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='sleep_hours',
            field=models.FloatField(default=8.0),
        ),
    ]
