# Generated by Django 5.0.6 on 2024-06-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_weeklyschedule_meal_hours_weeklyschedule_sleep_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='meal_hours',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='sleep_hours',
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
