# Generated by Django 5.0.6 on 2024-06-15 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_book_created_at_book_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_date',
        ),
        migrations.AddField(
            model_name='book',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
