# Generated by Django 5.0.6 on 2024-06-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_book_author_alter_book_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
