# Generated by Django 5.0.6 on 2024-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_book_order_alter_book_author_alter_book_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
