# Generated by Django 5.0.6 on 2024-06-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_book_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttask',
            name='duration',
        ),
    ]
